'use client'
import StoreProvider from '@/components/StoreProvider'
import Footer from '../components/footer/Footer'
import FooterBottom from '../components/footer/FooterBottom'
import NavBar from '../components/navBar/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <NavBar />
          <div className='w-full h-auto bg-bodyColor text-lightText' >
            <div className='max-w-screen-2xl mx-auto px-16'>
              {children}
            </div>
          </div>
          <Footer />
          <FooterBottom />
        </StoreProvider>
      </body>
    </html>
  )
}
